apps/usuario/urls.py
from django.urls import path

from apps.usuario.views import profile_detail_visita, profile_edit, list_user, profile_detail, adicionar_unidade, deletar_unidade, adicionar_projeto, deletar_projeto

urlpatterns = [
    path('detail/', profile_detail, name='profile_detail'),
    path('edit/<int:id>/', profile_edit, name='profile_edit'),
    path('list_user/', list_user, name='list_user'),
    path('profile_detail/', profile_detail, name='profile_detail'),
    path('profile_detail_visita/<int:id>/', profile_detail_visita, name='profile_detail_visita'),
    path('adicionar_unidade/<int:id>/', adicionar_unidade, name='adicionar_unidade'),
    path('deletar_unidade/<int:id>/', deletar_unidade, name='deletar_unidade'),
    path('adicionar_projeto/<int:id>/', adicionar_projeto, name='adicionar_projeto'),
    path('deletar_projeto/<int:id>/', deletar_projeto, name='deletar_projeto'),

]

hubintegrador/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('users/', include('apps.usuario.urls')),
    path('accounts/', include('apps.account.urls')),
    path('unidades/', include('apps.unidade.urls')),
    path('projetos/', include('apps.projeto.urls')),
    path('ged/', include('apps.ged.urls')),
    path('fornecedores/', include('apps.fornecedores.urls')),
    path('crono_master/', include('apps.cronograma_master.urls')),
    path('master_index/', include('apps.master_index.urls')),
    path('cronograma_contratada/', include('apps.cronogramacontratadas.urls')),
    path('compras/', include('apps.controlecompras.urls')),
]

apps/usuario/models.py
from django.db import models
#from django.contrib.auth.models import User
from django.conf import settings

from apps.core.models import Owner

ROLE_CHOICE=(
    (1,'Administrador'),
    (2,'Usuário'),
)

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    owner = models.ForeignKey(Owner, on_delete=models.PROTECT, blank=True, null=True)
    nome = models.CharField(max_length=300, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    user_photo = models.ImageField(blank=True, null=True)
    role = models.IntegerField(choices=ROLE_CHOICE, default=2)


    class Meta:
        db_table = 'profile'
        verbose_name_plural = 'BD Profile'
        verbose_name = 'BD Profile'


    def __str__(self):
        return self.nome

apps/usuario/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import inlineformset_factory

from apps.core.models import Usuario_Unidade, Unidade
from apps.projeto.models import Usuario_Projeto, Projeto
from apps.usuario.models import Profile



class UserProfileRegistrationForm(forms.ModelForm):
    nome = forms.CharField()
    date_of_birth = forms.DateField(
        label='Data de naiscimento',
        widget=forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date', 'class':'form-control'}))

    nome.widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Profile
        fields = ('nome', 'date_of_birth')



class UserProfileEditForm(forms.ModelForm):
    date_of_birth = forms.DateField(
        label='Data de naiscimento',
        widget=forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'}))
    class Meta:
         model = Profile
         fields = ('date_of_birth', 'user_photo')


RegisterFormset = inlineformset_factory(
    User,
    Profile,
    form = UserProfileRegistrationForm,
    extra=0,
    can_delete=False,
    min_num=1,
    validate_min=True,
)



class UserEditForm(forms.ModelForm):
    date_of_birth = forms.DateField(
        label='Data de naiscimento',
        widget=forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date', 'class': 'form-control'}))
    class Meta:
         model = Profile
         fields = ('nome', 'user_photo', 'date_of_birth')



class UnidadeAddForm(forms.ModelForm):
    unidade = forms.ModelChoiceField(queryset=Unidade.objects.none())
    unidade.widget.attrs.update({'class': 'form-control'})
    class Meta:
        model = Usuario_Unidade
        fields = ('unidade',)

    def __init__(self, *args, **kwargs):
        unidades_queryset = kwargs.pop('unidades_queryset', Unidade.objects.all())
        super().__init__(*args, **kwargs)
        self.fields['unidade'].queryset = unidades_queryset





class ProjetoUsuarioAddForm(forms.ModelForm):
    projeto = forms.ModelChoiceField(queryset=Projeto.objects.none())
    projeto.widget.attrs.update({'class': 'form-control'})
    class Meta:
        model = Usuario_Projeto
        fields = ('projeto',)

    def __init__(self, *args, **kwargs):
        projetos_queryset = kwargs.pop('projetos_queryset', Projeto.objects.all())
        super().__init__(*args, **kwargs)
        self.fields['projeto'].queryset = projetos_queryset

apps/usuario/views.py
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages
from apps.account.forms import UserEditFormAdmin, UserProfileEditFormAdmin
from apps.core.models import Usuario_Unidade, Unidade
from apps.projeto.models import Usuario_Projeto, Projeto
from apps.usuario.forms import UserProfileEditForm, RegisterFormset, UserEditForm, UnidadeAddForm, ProjetoUsuarioAddForm
from apps.usuario.models import Profile, ROLE_CHOICE
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q

@csrf_exempt
@login_required
def list_user(request):
    user = request.user
    profile = Profile.objects.get(user=user)

    usuarios = Profile.objects.filter(owner=profile.owner)
    user_form = RegisterFormset()
    choices = ROLE_CHOICE

    form_edit_user_admin = UserEditFormAdmin(request.POST or None)
    user_profile_edit = UserProfileEditFormAdmin(request.POST or None)

    return render(request, 'list_user.html',
                  {'usuarios': usuarios, 'user_form': user_form, 'choices': choices, 'profile': profile, 'form_edit_user_admin':form_edit_user_admin, 'user_profile_edit':user_profile_edit})

@csrf_exempt
@login_required
def profile_detail(request):
    id = request.user.id
    usuario = User.objects.get(id=id)
    profile = Profile.objects.get(user=usuario)
    form = UserProfileEditForm(request.POST or None, instance=profile)

    return render(request, 'profile.html', {'usuario':usuario,'profile':profile, 'form':form})


@csrf_exempt
@login_required
def profile_edit(request, id):
    usuario = User.objects.get(id=id)
    profile = Profile.objects.get(user=usuario)
    form = UserProfileEditForm(request.POST or None, instance=profile)

    if request.method == "POST":

        if form.is_valid():
            user_photo = request.FILES.get('user_photo')
            if user_photo != None:
                profile_user = form.save(commit=False)
                profile_user.user_photo= user_photo
                profile_user.save()
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            else:
                form.save()
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@csrf_exempt
@login_required
def profile_detail(request):
    usuario = request.user
    unidades = Usuario_Unidade.objects.filter(usuario_id=usuario)
    projetos = Usuario_Projeto.objects.filter(usuario_id=usuario)
    profile = Profile.objects.get(user=usuario)
    usuario_profile = request.user
    profile_perfil = Profile.objects.get(user=request.user)
    usuario_query = profile_perfil.user
    unidades_queryset = Unidade.objects.filter(owner=profile_perfil.owner)
    form_profile = UserEditForm(request.POST or None, instance=profile)
    form_unidade = UnidadeAddForm(request.POST or None, unidades_queryset=unidades_queryset)
    projetos_queryset = Projeto.objects.filter(Q(unidade__in=usuario_query.usuario_unidade_set.all().values('unidade')))
    form_projeto_usuario = ProjetoUsuarioAddForm(request.POST or None, projetos_queryset=projetos_queryset)


    return render(request, 'profile.html', {'projetos':projetos, 'usuario_profile':usuario_profile, 'usuario':usuario, 'form_profile':form_profile, 'form_unidade':form_unidade,'unidades':unidades, 'profile':profile, 'profile_perfil':profile_perfil, 'form_projeto_usuario':form_projeto_usuario})


@csrf_exempt
@login_required
def profile_detail_visita(request, id):
    usuario = request.user
    profile = Profile.objects.get(user=usuario)


    usuario_profile = User.objects.get(id=id)
    profile_perfil = Profile.objects.get(user=usuario_profile)


    unidades = Usuario_Unidade.objects.filter(usuario_id=profile_perfil.user)
    projetos = Usuario_Projeto.objects.filter(usuario_id=profile_perfil.user)

    form_profile = UserEditForm(request.POST or None, instance=profile_perfil)

    usuario_query = profile_perfil.user
    unidades_queryset = Unidade.objects.filter(owner=profile_perfil.owner)
    form_unidade = UnidadeAddForm(request.POST or None, unidades_queryset=unidades_queryset)

    projetos_queryset = Projeto.objects.filter(Q(unidade__in=usuario_query.usuario_unidade_set.all().values('unidade')))
    form_projeto_usuario = ProjetoUsuarioAddForm(request.POST or None, projetos_queryset=projetos_queryset)




    return render(request, 'profile.html',
                  {'projetos': projetos, 'usuario': usuario, 'form_profile': form_profile, 'form_unidade': form_unidade,
                   'unidades': unidades, 'profile': profile, 'profile_perfil': profile_perfil,
                   'form_projeto_usuario': form_projeto_usuario, 'usuario_profile':usuario_profile})

@csrf_exempt
@login_required
def profile_edit(request, id):
    usuario = User.objects.get(id=id)
    profile = Profile.objects.get(user=usuario)
    form_profile = UserEditForm(request.POST or None, instance=profile)

    if request.method == "POST":
        if form_profile.is_valid():
            form_profile.save()
            user_photo = request.FILES.get('user_photo')
            if user_photo != None:
                profile_user = form_profile.save(commit=False)
                Profile.objects.filter(id=profile_user.id).update(user_photo=user_photo)
                profile_user.save()
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            else:
                form_profile.save()
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@csrf_exempt
@login_required
def adicionar_unidade(request, id):
    usuario = User.objects.get(id=id)

    profile = Profile.objects.get(user=usuario)
    unidades_queryset = Unidade.objects.filter(owner=profile.owner)
    unidade_instance = Usuario_Unidade()
    form_unidade = UnidadeAddForm(request.POST or None, instance=unidade_instance, unidades_queryset=unidades_queryset)
    print(form_unidade.is_valid())

    if request.method == "POST":
        if form_unidade.is_valid():
            unidade_nova = request.POST.get('unidade')
            count = Usuario_Unidade.objects.filter(unidade=unidade_nova, usuario=usuario).count()
            if count > 0:
                messages.error(request, 'Unidade já cadastrada para o usuario!!')
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            unidade = form_unidade.save(commit=False)
            unidade.usuario = usuario
            unidade.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@csrf_exempt
@login_required
def deletar_unidade(request, id):
    unidade = Usuario_Unidade.objects.get(id=id)
    unidade.delete()
    messages.success(request, "Disciplina Excluida com sucesso !")
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@csrf_exempt
@login_required
def adicionar_projeto(request, id):
    usuario = User.objects.get(id=id)
    profile = Profile.objects.get(user=usuario)
    projetos_queryset = Projeto.objects.filter(owner=profile.owner)
    projeto_instance = Usuario_Projeto()
    form_projeto_usuario = ProjetoUsuarioAddForm(request.POST or None, instance=projeto_instance,projetos_queryset=projetos_queryset)

    if request.method == "POST":
        if form_projeto_usuario.is_valid():
            projeto_novo = request.POST.get('projeto')
            count = Usuario_Projeto.objects.filter(projeto=projeto_novo, usuario=usuario).count()
            if count > 0:
                messages.error(request, 'Projeto já cadastrada para o usuario!!')
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            projeto = form_projeto_usuario.save(commit=False)
            projeto.usuario = usuario
            projeto.unidade = projeto.projeto.unidade
            projeto.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@csrf_exempt
@login_required
def deletar_projeto(request, id):
    projeto = Usuario_Projeto.objects.get(id=id)
    projeto.delete()
    messages.success(request, "Projeto Excluido com sucesso !")
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

apps/usuario/templates/list_user.html
{% extends 'base.html' %}
{% load custom_filter_tags %}
{% load static %}


{% block main %}

<div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Usuários Cadastrados</h4>
                                <span class="btn btn-primary"><a type="button" href="{% url 'register' %}">Cadastrar Usuário</a></span>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead class="thead-primary">
                                            <tr>
                                                <th scope="col">Nome</th>
                                                <th scope="col">email</th>
                                                <th scope="col">Perfil</th>
                                                <th scope="col">Status</th>
                                                <th scope="col">Ações</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for usuario in usuarios %}
                                            <tr>
                                                <th><a href="{% url 'profile_detail_visita'  usuario.id %}">{{usuario.nome}}</a></th>
                                                <td>{{usuario.user.email}}</td>
                                                <td>{{usuario.role| tipo_registro}}</td>
                                                <td>{{usuario.user.id| status_usuario}}</td>
                                                <td>

                                                     <button type="button" class="btn btn-primary" onclick="atividade({{usuario.user.id}})" > <span class="fa fa-edit"></span></button>
                                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModalConfirmDeletCargo" onclick="atividadedelet({{usuario.user.id}})" > <span class="fa fa-trash"></span></button>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
<div id="myModalEdit" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <form name="form" id="form" class="form-horizontal" method="post" action="{% url 'usuario_edit_admin' %}">
    {% csrf_token %}
    <!-- Modal content-->
    <div class="modal-content" >
      <div class="modal-header">
          <h3 class="modal-title">Editar Usuário </h3>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
          <div class="form-group">
              <input type="hidden" name="id_edit"  id="id_edit" value="">
              {{user_profile_edit.as_p}}
              {{form_edit_user_admin.as_p}}


          </div>
      </div>
      <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Editar</button>
      </div>
    </div>
    </form>
  </div>
</div>

<div id="myModalConfirmDeletCargo" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <form name="form" id="formdelettask" class="form-horizontal" method="post" action="{% url 'usuario_deletar' %}">
    {% csrf_token %}
    <!-- Modal content-->
    <div class="modal-content" >
      <div class="modal-header">
          <h3 class="modal-title">Deletar Usuário </h3>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
          <div class="form-group">
              <input type="hidden" name="id_delet"  id="id_delet" value="">
                <h3>Você deseja deletar esse Usuário? Essa ação não tem volta!</h3>
          </div>
      </div>
      <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Deletar</button>
      </div>
    </div>
    </form>
  </div>
</div>

{% endblock %}

{% block jsadd %}

<script>
    function atividade(id){
        console.log(id);
        $.ajax({
            url: "/accounts/usuario_edit_admin_ajax/" + id,
            async: true,
            type: 'GET',
            success: function(data) {
                console.log(data);

                $('#form').trigger("reset");

                $('#id_role').val(data.role);
                $('#id_is_active').prop('checked', data.is_active);

                $('#id_edit').val(id);

                $('#myModalEdit').modal('show');

            }
        });
    };

    function atividadedelet(id){
      document.getElementById("id_delet").value = id;
      console.log(id)
    };

</script>
{% endblock  %}

apps/usuario/templates/profile.html
{% extends 'base.html' %}
{% load custom_filter_tags %}
{% load static %}

{% block main %}
{% include 'message.html' %}

   </head>
   <body class="inner_page profile_page">
      <div class="full_container">
         <div class="inner_container">
               <!-- end topbar -->
               <!-- dashboard inner -->
               <div class="midde_cont">
                  <div class="container-fluid">

                     <!-- row -->
                     <div class="row column1">
                        <div class="col-md-2"></div>
                        <div class="col-md-8">
                           <div class="white_shd full margin_bottom_30">
                              <div class="full graph_head">
                                 <div class="heading1 margin_0">
                                    <h2>Perfil do usuario</h2>
                                 </div>
                                 <div>

                                     <button type="button" class="btn  btn-success dropdown-toggle  float-right" data-toggle="dropdown" aria-expanded="false">+ Ações</button>
                                    <div class="dropdown-menu" x-placement="top-start" style="position: absolute; transform: translate3d(0px, -2px, 0px); top: 0px; left: 0px; will-change: transform;">
                                                        {% if profile_perfil.role == 1 %}
                                                      <button type="button" class="dropdown-item" data-toggle="modal" data-target="#myModalUnidade">Adicionar Unidade</button>
                                                      <button type="button" class="dropdown-item" data-toggle="modal" data-target="#myModalProjeto">Adicionar Projeto</button>
                                                        {% endif %}

                                                        {% if profile_perfil.user.id == user.id %}
                                                      <a type="button" class="dropdown-item" href="{% url 'password_change' %}">Trocar Senha</a>
                                                        {% endif %}
                                 </div>
                              </div>
                              <div class="full price_table padding_infor_info">
                                 <div class="row">
                                    <!-- user profile section --> 
                                    <!-- profile image -->
                                    <div class="col-lg-12">
                                       <div class="full dis_flex center_text">

                                           {% if profile_perfil.user_photo %}
                                           <div class="profile_img"><img width="180" class="rounded-circle" src="{{ profile_perfil.user_photo.url }}" alt="Foto Perfil" /></div>
                                           {% else %}
                                          <div class="profile_img"><img width="180" class="rounded-circle" src="{% static 'images/layout_img/user_img.png' %}" alt="Foto Perfil" /></div>
                                          {% endif %}
                                           <div class="profile_contant">
                                             <div class="contact_inner">
                                                 <div class="row" style="display: inline-block">
                                                     <h3>{{profile_perfil.nome}}</h3>
                                                     {% if profile_perfil.user.id == usuario.id %}
                                                    <h1>   </h1>
                                                    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal"><i class="fa fa-pencil"></i></button>
                                                    {% endif %}
                                                 </div>

                                                <p><strong>Registro: </strong>{{profile_perfil.role|tipo_registro}}</p>
                                                <ul class="list-unstyled">
                                                   <li><i class="fa fa-envelope-o"></i> : {{usuario_profile.email}}</li>

                                                </ul>
                                             </div>
                                          </div>
                                       </div>
                                       <!-- profile contant section -->
                                       <div class="full inner_elements margin_top_30">
                                          <div class="tab_style2">
                                             <div class="tabbar">
                                                <nav>
                                                   <div class="nav nav-tabs" id="nav-tab" role="tablist">
                                                      <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#recent_activity" role="tab" aria-selected="true">Unidades</a>
                                                      <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#profile_section" role="tab" aria-selected="false">Projetos</a>
                                                   </div>
                                                </nav>
                                                <div class="tab-content" id="nav-tabContent">
                                                   <div class="tab-pane fade show active" id="recent_activity" role="tabpanel" aria-labelledby="nav-home-tab">
                                                      <div class="table-responsive-sm">
                                    <table class="table">
                                       <thead>
                                          <tr>
                                             <th><center>Unidade </center></th>
                                              {% if profile_perfil.role == 1 %}
                                             <th><center>Deletar </center></th>
                                              {% endif %}
                                          </tr>
                                       </thead>
                                       <tbody>
                                       {% for unidade in unidades %}
                                          <tr>
                                             <td><center>{{unidade.unidade}}</center></td>
                                              {% if profile_perfil.role == 1 %}
                                             <td>

                                                 <center>
                                                        <a class="btn btn-danger" data-placement="right" href="{% url 'deletar_unidade' unidade.id %}">Deletar</a>
                                                 </center>

                                             </td>
                                              {% endif %}

                                          </tr>
                                       {% endfor %}
                                       </tbody>
                                    </table>
                                 </div>
                                                   </div>
                                                   <div class="tab-pane fade" id="project_worked" role="tabpanel" aria-labelledby="nav-profile-tab">


                                                   </div>
                                                   <div class="tab-pane fade" id="profile_section" role="tabpanel" aria-labelledby="nav-contact-tab">
                                                      <table class="table">
                                       <thead>
                                          <tr>
                                             <th><center>Projeto </center></th>
                                              {% if profile_perfil.role == 1 %}
                                             <th><center>Deletar </center></th>
                                              {% endif %}
                                          </tr>
                                       </thead>
                                       <tbody>
                                       {% for projeto in projetos %}
                                          <tr>
                                             <td><center>{{projeto.projeto}}</center></td>
                                              {% if profile_perfil.role == 1 %}
                                             <td>

                                                 <center>
                                                        <a class="btn btn-danger" data-placement="right" href="{% url 'deletar_projeto' projeto.id %}">Deletar</a>
                                                 </center>
                                             </td>
                                              {% endif %}

                                          </tr>
                                       {% endfor %}
                                       </tbody>
                                    </table>
                                                   </div>
                                                </div>
                                             </div>
                                          </div>
                                       </div>
                                       <!-- end user profile section -->
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <div class="col-md-2"></div>
                        </div>
                        <!-- end row -->
                     </div>
                     <!-- footer -->
                     <div class="container-fluid">
                        <div class="footer">

                           </p>
                        </div>
                     </div>
                  </div>
                  <!-- end dashboard inner -->
               </div>
            </div>
         </div>
      </div>

   </body>
<form name="form" id="form" class="form-horizontal" method="post"  action="{% url 'profile_edit' usuario.id %}" enctype="multipart/form-data">
{% csrf_token %}
    <!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content" >
      <div class="modal-header">
          <h3 class="modal-title">Editar</h3>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
          <div class="form-group">
              <div class="col-sm-8" >
                  <fieldset>
                      <div class="field">
                        {{ form_profile.as_p }}
                      </div>
                  </fieldset>
              </div>
          </div>

      </div>
      <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Salvar</button>
      </div>
    </div>

  </div>
</div>
</form>

<form name="form" id="formunidade" class="form-horizontal" method="post" action="{% url 'adicionar_unidade' usuario_profile.id %}">
{% csrf_token %}
    <!-- Modal -->
<div id="myModalUnidade" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content" >
      <div class="modal-header">
          <h3 class="modal-title">Adicionar Unidade</h3>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
          <div class="form-group">
              <div class="col-sm-8" >
                  <fieldset>
                      <div class="field">
                        {{ form_unidade.as_p }}
                      </div>
                  </fieldset>
              </div>
          </div>

      </div>
      <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Salvar</button>
      </div>
    </div>

  </div>
</div>
</form>


<form name="form" id="formprojeto" class="form-horizontal" method="post" action="{% url 'adicionar_projeto' usuario_profile.id %}">
{% csrf_token %}
    <!-- Modal -->
<div id="myModalProjeto" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content" >
      <div class="modal-header">
          <h3 class="modal-title">Adicionar Projeto</h3>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
          <div class="form-group">
              <div class="col-sm-8" >
                  <fieldset>
                      <div class="field">
                        {{ form_projeto_usuario.as_p }}
                      </div>
                  </fieldset>
              </div>
          </div>

      </div>
      <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Salvar</button>
      </div>
    </div>

  </div>
</div>
</form>
{% endblock %}